#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.34014
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("HVC_Test.Resource", IsApplication=true)]

namespace HVC_Test
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::omron.HVC.Droid.Resource.String.ApplicationName = global::HVC_Test.Resource.String.ApplicationName;
			global::omron.HVC.Droid.Resource.String.Hello = global::HVC_Test.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Refresh = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050002
			public const int FindButton = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int StartButton = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int StatusTextView = 2131034116;
			
			// aapt resource value: 0x7f050001
			public const int devices = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int title_devices = 2131034112;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Devices = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int App_Name = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040007
			public const int BleNotSupported = 2130968583;
			
			// aapt resource value: 0x7f040005
			public const int EndButton = 2130968581;
			
			// aapt resource value: 0x7f040003
			public const int FindButton = 2130968579;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040009
			public const int PopupMssage = 2130968585;
			
			// aapt resource value: 0x7f04000b
			public const int PopupNo = 2130968587;
			
			// aapt resource value: 0x7f040008
			public const int PopupTitle = 2130968584;
			
			// aapt resource value: 0x7f04000a
			public const int PopupYes = 2130968586;
			
			// aapt resource value: 0x7f040006
			public const int SelectDevice = 2130968582;
			
			// aapt resource value: 0x7f040004
			public const int StartButton = 2130968580;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
